# This Python file uses the following encoding: utf-8
from nltk.corpus import stopwords

def getStopWords():
    stop_words = stopwords.words('portuguese')
    stop_words.append(':p')
    stop_words.append(':s')
    stop_words.append(':o')
    stop_words.append(':d')
    stop_words.append('?')
    stop_words.append('!')
    stop_words.append(',')
    stop_words.append('.')
    stop_words.append('...')
    stop_words.append('@')
    stop_words.append('#')
    stop_words.append('"')
    stop_words.append('(')
    stop_words.append(')')
    stop_words.append('*')
    stop_words.append(';')
    stop_words.append(':')
    stop_words.append('<')
    stop_words.append('>')
    stop_words.append('[')
    stop_words.append(']')
    stop_words.append('|')
    stop_words.append('^')
    stop_words.append('=')
    stop_words.append('{')
    stop_words.append('}')
    stop_words.append('_')
    stop_words.append('-')
    stop_words.append('+')
    stop_words.append('/')
    stop_words.append('&')
    stop_words.append(u"'")
    stop_words.append(u"''")
    stop_words.append(u'``')
    stop_words.append(u'é')
    stop_words.append(u'p/')
    stop_words.append(u'...')
    stop_words.append(u'')
    stop_words.append(u'$')
    stop_words.append(u'rt')
    stop_words.append(u'es')
    stop_words.append(u'la')
    stop_words.append(u'los')
    stop_words.append(u'el')
    stop_words.append(u'http')
    stop_words.append(u'https')
    
    return stop_words